config/routes.rb
Rails.application.routes.draw do
  get '/dives' => 'dives#index'
  post '/dives' => 'dives#create'
  get '/dives/new' => 'dives#new', as: 'new_dive'
  get '/dives/:id/edit' => 'dives#edit', as: 'edit_dive'
  get '/dives/:id' => 'dives#show', as: 'dive'
  put '/dives/:id' => 'dives#update'
  patch '/dives/:id' => 'dives#update'
  delete '/dives/:id' => 'dives#destroy'
  delete '/dives/:id/fish/:fish_id' => 'dives#removefish'
  post '/dives/:id/fish' => 'dives#addfish'

  post '/dives/:id/divers' => 'dives#adddiver'
  delete '/dives/:id/divers/:diver_id' => 'dives#removediver'

  get '/divers' => 'divers#index'
  get '/divers/:id' => 'divers#show', as: 'diver'

  post '/photos' => 'photos#create'
  delete '/photos/:id' => 'photos#destroy'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'root#index'

end

app/models/dive.rb
class Dive < ActiveRecord::Base
  has_many :fish, through: :dive_fishes
  has_many :dive_fishes
  belongs_to :operator
  has_many :divers, through: :diver_dives
  has_many :diver_dives
  has_many :photos

  accepts_nested_attributes_for :photos, :allow_destroy => true

  validates_presence_of :date, :dive_site
  validate :time_in_must_be_before_time_out


  validates :start_air, :end_air, :visibility, numericality: true, :allow_nil => true
  validates :depth, :temperature, numericality: { only_integer: true }, :allow_nil => true

  before_save :set_defaults

  def display_date 
    date.strftime("%B %e, %Y")
  end

  def display_time_in
    time_in.strftime("%I:%M %p")
  end

  def display_time_out
    time_out.strftime("%I:%M %p")
  end

  protected

  def set_defaults
    self.notes = "No Notes Recorded" if self.notes == nil
  end


  def time_in_must_be_before_time_out
    if time_in && time_out
      errors.add(:time_in, "must be before end time") unless
        time_in < time_out
    end
  end 

end

app/models/dive_fish.rb
class DiveFish < ActiveRecord::Base
  belongs_to :dive
  belongs_to :fish
end

app/models/diver.rb
class Diver < ActiveRecord::Base
  has_many :dives, through: :diver_dives
  has_many :diver_dives

  validates_presence_of :name

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |diver|
      diver.provider = auth.provider
      diver.uid = auth.uid
      diver.name = auth.info.name
      diver.email = auth.info.email
      diver.image = auth.info.image
      diver.oauth_token = auth.credentials.token
      diver.oauth_expires_at = Time.at(auth.credentials.expires_at)
      diver.save!
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end  


end

app/models/diver_dive.rb
class DiverDive < ActiveRecord::Base
  belongs_to :diver
  belongs_to :dive
end

app/models/fish.rb
class Fish < ActiveRecord::Base
  has_many :dives, through: :dive_fishes
  has_many :dive_fishes
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  has_many :dives
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :dive
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_diver
    @current_diver ||= Diver.find(session[:diver_id]) if session[:diver_id]
  end
  helper_method :current_diver

  def logged_in?
  	!!current_diver
  end
  helper_method :logged_in?

  def authorized_diver?(dive)
    logged_in? && dive.divers.include?(current_diver)
  end
  helper_method :authorized_diver?  

end

app/controllers/divers_controller.rb
class DiversController < ApplicationController

  def index
    respond_to do |format|
      format.json { render json: (Diver.all.collect { |diver| "#{diver.name}" }) }
      format.html { redirect_to root_path }
    end

  end

  def show
    @diver = Diver.find_by(id: params[:id])
    if !@diver
      redirect_to dives_path, :flash => { :error => "That diver does not exist" }
    end
  end
end

app/controllers/dives_controller.rb
class DivesController < ApplicationController

  before_action :set_dive, only: [:show, :edit, :update, :destroy]

  def index
    if logged_in?
      @dives = current_diver.dives
    else
      redirect_to root_path, :flash => { :error => "You must be signed in to see this page" }
    end
  end

  def show
    @photo = @dive.photos.new
    @fish = Fish.new
    @diver = Diver.new
  end

  def new
    if logged_in?
      @dive = Dive.new
    else
      redirect_to root_path, :flash => { :error => "Please sign in to log a dive" }
    end
  end

  def create
    @dive = Dive.new(dive_params)
    @diver = current_diver
    if logged_in? && @dive.save
      if params[:photos]
        params[:photos]['image'].each { |p| @dive.photos.create!(:image => p, :dive_id => @dive.id) }  
      end
      @diver.dives << @dive
      redirect_to dive_path(@dive)
    else
      if dive_params[:dive_site] == ""
        flash[:error] = "Please enter a dive site"
        render "new"
      else
        flash[:error] = "Please enter a date"
        render "new"
      end
    end
 
  end

  def edit
    if !logged_in?
      redirect_to root_path, :flash => { :error => "Please log in" }
    elsif !dive_team_member?
      redirect_to diver_path, :flash => { :error => "You can't edit someone else's dive!" }
    end
  end

  def update
    respond_to do |format|
      if !( !real_time?(dive_params) || @dive.update(dive_params))
        format.html { redirect_to(@dive, :notice => 'Dive was successfully updated.') }
        format.json { respond_with_bip(@dive) }
      else
        format.html { head :ok, :error => 'Something went wrong.' }
        format.json { head :ok }
      end
    end    
  end

  def real_time?(update_params)
    begin
      if update_params["time_in"]
        Time.parse(update_params["time_in"])
      end

      if update_params["time_out"]
        Time.parse(update_params["time_out"])
      end         
    rescue
      return false
    end
    return true
  end

  def destroy
    if logged_in? && dive_team_member?
      @dive.destroy
      redirect_to diver_path
    else
      redirect_to dive_path(@dive), :flash => { :error => "You can't delete someone else's dive!" }
    end
  end

  def addfish
    @fish = Fish.find_by(:name => params[:name])

    @dive = Dive.find(params[:id])
    @dive.fish << @fish if !@dive.fish.include?(@fish)
    render :json => @dive.fish
  end


  def adddiver
    @diver = Diver.find_by(name: params[:name])
    @dive = Dive.find(params[:id])
    @dive.divers << @diver if !@dive.divers.include?(@diver)
    render :json => @diver
  end

  def removediver
    @dive = Dive.find(params[:id])
    @diver = Diver.find_by(:id => params[:diver_id])
    @diverdive = DiverDive.find_by(:dive_id => @dive.id, :diver_id => @diver.id)
    if @dive.diver_dives.first == @diverdive
      render :json => { :errors => "This doesn't work"}
    else
      @diverdive.destroy
      render :json => { :head => :ok }
    end
  end

  def removefish
    @dive = Dive.find(params[:id])
    @fish = Fish.find(params[:fish_id])
    @dive_fish = DiveFish.find_by(:dive_id => @dive.id, :fish_id => @fish.id)
    @dive_fish.destroy
    render :json => { :head => :ok }
  end

  private

  def dive_team_member?
    @dive.divers.include?(current_diver)
  end

  def set_dive
    @dive = Dive.find_by(id: params[:id])
    redirect_to diver_path if @dive == nil
  end

  def dive_params
    params.require(:dive).permit(:date, :depth, :temperature, :time_in, :time_out, :dive_site, :visibility, :start_air,
      :end_air, :dive_type, :dive_activity, :wetsuit, :conditions, :notes)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def create
  	@photo = Photo.create(photo_params)
  end

  def destroy
  	@photo = Photo.find(params[:id])
  	@photo.destroy
    head :ok
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :dive_id)
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    diver = Diver.from_omniauth(env["omniauth.auth"])
    session[:diver_id] = diver.id
    redirect_to root_url
  end

  def destroy
    session[:diver_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/divers/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">
        <%= image_tag @diver.image %>
        <br>
        <h2>
          <%= @diver.name %>
        </h2>
        <h3>
          <%= @diver.email %>
          <br>
          <%= pluralize(@diver.dives.length, 'Dive') %> logged
        </h3>    
      </div>
      <div class="col-md-6">
        <% if @diver.dives.length != 0 %>
          <h3>
            Dive list:
          </h3>
          <ul>
            <% @diver.dives.order(date: :desc).each do |d| %>
              <li><%= link_to d.dive_site, d %> -- <%= d.date %></li>
            <% end %>
          </ul>
        <% else %>
          <h3>
            No dives logged.
          </h3>
          <h4>
            <%= link_to "Log a Dive!", new_dive_path %>
          </h4>
        <% end %>
      </div>  
    </div>
    <div class="row">
    </div>
  </div>
</div>

app/views/dives/_dive_details.html.erb
<div class="col-md-4">
  <h3>
    <%= best_in_place_if authorized_diver?(@dive), @dive, :date, type: :date, display_as: :display_date %>
  </h3>
  <h4 class="times">
    Time In: <%= best_in_place_if authorized_diver?(@dive), @dive, :time_in, display_as: :display_time_in %>
    <br/> 
    Time Out: <%= best_in_place_if authorized_diver?(@dive), @dive, :time_out, display_as: :display_time_out %>
    <br/>
  </h4>

  <div id="divers">
    <% @dive.diver_dives.order(:id).each do |d| %>
        <span class="diver-thumb">
          <% @diver = Diver.find(d.diver_id) %>
          <%= link_to((image_tag @diver.image, class:"img-circle"), @diver) %>
          <span class="diver-remove">
            <span class="glyphicon glyphicon-remove diver-remove-icon" data-dive-id=<%= @dive.id %> data-diver-id=<%= @diver.id %>></span>
          </span>
        </span>
    <% end %>
  </div>
</div>

<div class="col-md-4 change-units">
  <p>
    Dive Type: <%= best_in_place_if authorized_diver?(@dive), @dive, :dive_type, type: :select, collection: [["", "—"], ["boat", "Boat Dive"], ["beach", "Beach Dive"], ["drift", "Drift Dive"], ["night", "Night Dive"]] %>
    <br/>   
    Dive Activity: <%= best_in_place_if authorized_diver?(@dive), @dive, :dive_activity, type: :select, collection: [["", "—"], ["wreck", "Wreck Dive"], ["reef", "Reef Dive"], ["cave", "Cave Dive"], ["training", "Training Dive"]] %>
    <br/>
    <span class="depth-contents">       
      Maximum Depth: <%= best_in_place_if authorized_diver?(@dive), @dive, :depth, type: :input %>
      <%= content_tag :span, " meters", class: 'depth' %>
    </span>
    <br/>
    <span class="temperature-contents">  
      Water Temperature: <%= best_in_place_if authorized_diver?(@dive), @dive, :temperature, type: :input %>
      <%= content_tag :span, " °C", class: 'temperature' %>
    </span>
    <br/>
    <span class="visibility-contents">  
      Visibility: <%= best_in_place_if authorized_diver?(@dive), @dive, :visibility, type: :input %>
      <%= content_tag :span, " meters", class: 'visibility' %>
    </span>
    <br/>
    Conditions: <%= best_in_place_if authorized_diver?(@dive), @dive, :conditions, type: :input %>
    <br/>                
    <span class="start_air-contents">  
      Starting Air: <%= best_in_place_if authorized_diver?(@dive), @dive, :start_air, type: :input %>
      <%= content_tag :span, " bar", class: 'start_air' %>
    </span>
    <br/>
    <span class="end_air-contents">  
      Ending Air: <%= best_in_place_if authorized_diver?(@dive), @dive, :end_air, type: :input %>
      <%= content_tag :span, " bar", class: 'end_air' %>
    </span>
    <br/>
    Wetsuit? <%= best_in_place_if authorized_diver?(@dive), @dive, :wetsuit, type: :checkbox, collection: %w[No Yes] %>
  </p>
</div>
<div class="col-md-4 change-units">
  <p>
    Notes: <%= best_in_place_if authorized_diver?(@dive), @dive, :notes, type: :textarea %>
  </p>
</div>

app/views/dives/_dive_photos.html.erb
<% @dive.photos.each do |photo| %>
  <div class="col-md-6 thumb photo-thumb">
    <a class="fancybox" rel="group" href="<%= photo.image_url %>">
      <button class="btn photo-remove" data-photo-id="<%= photo.id %>">X</button>
      <img class="image-thumb thumbnail" src="<%= photo.image_url(:thumb) %>"  alt="" />
    </a>
  </div>
<% end %> 

app/views/dives/_fishes.html.erb
<% @dive.fish.each do |fish| %>
  <div class="col-md-6">
    <a href = "<%= fish.wiki_link %>" target="_blank">
	    <div class="thumbnail fish-thumb">
	    	<button class="btn fish-remove" data-fish-id=<%= fish.id %>, data-dive-id=<%= @dive.id %>>X</button>
	      <%= image_tag "http://#{fish.picture_link}" %>
	      <div class="caption">
	        <h4><%= fish.name %></h4>
	      </div>
	    </div>
	  </a>
  </div>
<% end %>

app/views/dives/_form.html.erb
<%= form_for @dive, :html => {:multipart => true} do |f| %>
	<div class="row text-center">
		<div class="col-sm-6">
			<h3>
			<%= f.label :dive_site, "Site:" %>
			<%= f.text_field :dive_site, required: true, :id => "dive-site" %>
			</h3>
		</div>
		<div class="col-sm-6">
			<h3>
			<%= f.label :date, "Date:" %>
			<%= f.date_field :date, required: true %>
			</h3>
		</div>
		<br>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-4">
			<p>
				<%= f.label :depth, "Maximum Depth:" %>
				<%= f.number_field :depth%> meters
			</p>
			<p>
				<%= f.label :temperature, "Water Temperature:" %>
				<%= f.number_field :temperature%> °C
			</p>
			<p>
				<%= f.label :time_in, "Time In:" %>
				<%= f.time_field :time_in%> 
				<%= f.label :time_out, "Time Out:" %>
				<%= f.time_field :time_out%>
			</p>
			<p>
				<%= f.label :visibility, "Visibility:" %>
				<%= f.number_field :visibility%> meters
			</p>
			<p>
				<%= f.fields_for :photo do |p| %>
				<%= f.label :image, "Add Photos:" %>
				<%= p.file_field :image, :multiple => true, name: "photos[image][]" %>
			<% end %>
			</p>
		</div>
		<div class="col-md-4">
			<p>
				<%= f.label :start_air, "Start Air:" %>
				<%= f.number_field :start_air%> bar
			</p>
			<p>
				<%= f.label :end_air, "End Air:" %>
				<%= f.number_field :end_air%> bar
			</p>

			<p>
				<%= f.label :dive_type, "Dive Type:" %>
				<%= f.select :dive_type, [["—", nil], ["Boat Dive", "boat"],["Beach Dive", "beach"],["Drift Dive", "drift"],["Night Dive", "Night"]] %>
			</p>

			<p>
				<%= f.label :dive_activity, "Dive Activity:" %>
				<%= f.select :dive_activity, [["—", nil], ["Wreck Dive", "wreck"],["Reef Dive", "reef"],["Cave Dive", "cave"],["Training Dive", "training"]] %>
			</p>

			<p>
				<%= f.check_box (:wetsuit) %>
				<%= f.label :wetsuit, "Wetsuit?" %>
			</p>

			<p>
				<%= f.label :conditions, "Water Conditions:" %>
				<%= f.text_field :conditions%>
			</p>
		</div>
		<div class="col-md-4">
			<%= f.text_area :notes, :placeholder => "Notes", :id => "dive-notes"%>		  	
		</div>
	</div>
	
   <div class="row gallery dive-photos">
    <%= render 'dive_photos' %>     
  </div>

	<div class="row">
		<div class="col-md-6">
			
		</div>
	</div>
		
	<div class="row">
  	<div class="span6" style="text-align:center">
   	 <%= f.submit "Submit Dive!", class:"btn btn-primary" %>
  	</div>
	</div>
<% end %>

app/views/dives/edit.html.erb
	<div class="panel panel-default">
	  <div class="panel-body">
	  	<div class="row">
				<h2 class="text-center">Edit a Dive</h2>
			</div>
			<%= render 'form' %>
	  </div>
	</div>

app/views/dives/index.html.erb
<%# search_form_for @q do |f| %>
  <%# f.label :dive_site_cont, "Search by Dive Site:" %>
  <%# f.text_field :dive_site_cont %>
  <%# f.submit %>
<%# end %>
<div class="panel panel-default">
	<div class="panel-body toscroll">
  	<h1 class ="text-center"> Dive Log </h1>
  	<div class="row text-center">
  		<a href = "<%= new_dive_path %>" class="btn btn-primary text-center"> Add a Dive </a>
  	</div>
  	<table class = "table table-hover">
			<thead>
				<tr>
					<th>ID</th>
					<th>Site</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				<% @dives.order(date: :desc).each do |dive| %>
					<tr class='clickableRow dive-row' href='<%= dive_path(dive) %>'>
						<td><%= dive.id %></td>
						<td><%= dive.dive_site %></td>
						<td><%= dive.date %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/dives/new.html.erb
	<div class="panel panel-default">
	  <div class="panel-body">
	  	<div class="row">
				<h1 class="text-center">Log a New Dive</h1>
			</div>
			<%= render 'form' %>
	  </div>
	</div>

app/views/dives/show.html.erb
<% if authorized_diver?(@dive) %>
  <script id="template-upload" type="text/x-tmpl">
    <div class="upload">
    </div>
  </script>
<% end %>

<div class="panel panel-default dives show" data-member="<%= authorized_diver?(@dive) %>">
  <div class="panel-body">
    <div class="row text-right">
      <div class="col-lg-12">
        <% if authorized_diver?(@dive) %>
        <a href="/dives/<%= @dive.id %>" data-method="delete">
          <span class="glyphicon glyphicon-trash diver-remove-icon" data-dive-id=<%= @dive.id %>></span>
        <% end %>

        </a>
      </div>
    </div>
    <div class="row text-center">
      <h1 class="text-center">
        <%= best_in_place_if authorized_diver?(@dive), @dive, :dive_site, type: :input %>
      </h1>
    </div>
    
    <div class="row">
      <div class="col-lg-12 text-center">
        <% if authorized_diver?(@dive) %>
          <%= form_tag "#", id: "diver_search", data:{id: @dive.id }, remote:true do %>
            <div class="ui-widget">
              <label for="diver_name">Add a Friend to this Dive: </label>
              <input id="diver_name" name="diver_name">
              <%= submit_tag "Add Diver", class: 'btn btn-primary text-center' %>
            </div>
          <% end %>
        <% end %>
      </div>
      
      <div class="col-md-4 text-center">
      </div>
    </div>
    <br/>
    <div class="row">
      <%= render 'dive_details' %>
    </div>

    <div class="row">
      <div class="col-md-6">
        <h3 class="page-header text-center">Photos from Dive</h3>
        <div class="row"> <!-- search fish and add photo buttons -->
          <div class="col-md-12">
            <div class="uploaderbutton">
              <% if authorized_diver?(@dive) %>
                <div class="uploader">
                  <%= form_for @photo, remote:true do |f| %>
                    <%= f.hidden_field :dive_id, :value => @dive.id %>
                    <%= f.file_field :image, :multiple => true, name:"photo[image]" %>
                  <% end %>
                </div>
                <button class="btn btn-success fileinput-button">Upload a Photo</button>
              <% end %>
            </br>
            </br>
            </div>
            <div class="row gallery dive-photos">
              <%= render 'dive_photos' %>     
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <h3 class="page-header text-center">Fish Seen</h3>
        <div class="col-md-12">
          <% if authorized_diver?(@dive) %>
            <%= form_tag "#", id: "fish_search", data:{id: @dive.id } do %>
              <div class="ui-widget">
                <label for="name">Fish Name: </label>
                <input id="name" name="name">
                <%= submit_tag "Add Fish", class: 'btn btn-primary text-center' %>
              </div>
              <br/>
            <% end %>
          <% end %>
          <div class="row">
            <div id="fish">
              <%= render 'fishes' %>
            </div>
          </div>
        </div>
      </div>
      <br/>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Divelog</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Londrina+Outline' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application' %>
  <link href='http://fonts.googleapis.com/css?family=Londrina+Solid' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
</head>
<body class ="<%= controller_name %> <%= action_name %>">
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">divelog</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home</a></li>
        <li><a href="<%= dives_path %>">My Dives</a></li>
        <li><a href="<%= new_dive_path %>">Log a Dive</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if current_diver %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              <%= current_diver.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", diver_path(current_diver) %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
            </ul>  
          <% else %>
            <%= link_to "Sign In", "/auth/facebook", id: "sign_in" %>
          <% end %>  
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>


<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert("Failed to upload photo: <%= j @photo.errors.full_messages.join(', ').html_safe %>");
<% else %>

  $(".dive-photos").append('<div class="col-md-6 thumb photo-thumb">'+
                '<a class="fancybox" rel="group" href="<%= @photo.image_url %>">'+
                  '<button class="btn photo-remove" data-photo-id="<%= @photo.id %>">X</button>'+
                  '<img class="image-thumb thumbnail" src="<%= @photo.image_url(:thumb) %>"  alt="" />'+
                '</a>'+
            '</div>');
<% end %>

app/views/root/_errors.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger">
    <a href="/auth/facebook" class="alert-link"><%= flash[:error] %></a>
  </div>
<% end %>

app/views/root/index.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4 intro-text">
    <h1>
      welcome to divelog
    </h1>  
    <h3> 
      <% if logged_in? %>     
        <%= link_to "Log a Dive", new_dive_path, class: 'btn btn-info' %>
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", class: 'btn btn-info' %>
      <% end %>
    </h3>     
    <% if flash[:error] %>
      <div class="alert alert-warning">
        <p>Please <a href="/auth/facebook" class="alert-link">sign in</a> to log a dive</p>
      </div>
    <% end %>    
  </div>
  <div class="col-md-4"></div>
</div>
<br/>
<br/>
<br/>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div id="recentdives">
      <ul id="recentdives-list">
        <% Dive.order(id: :desc).limit(10).each do |dive| %>
          <li><%= link_to dive.diver_dives.first.diver.name, dive.diver_dives.first.diver %> dived 
            <%= link_to dive.dive_site, dive %> on <%= dive.display_date %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>